### ISSUE TITLE
WebRTC plugin is not working

### ISSUE THREAD

**Issue by ashbshaw** [ajb413/chat-engine-webrtc#6]
I followed all instructions listed on this site: https://www.pubnub.com/blog/webrtc-video-chat-engine-plugin-video-calling-chat/

I am receiving the following message and have narrowed my issues down to the WebRTC plugin. Is there a known issue, or do you have any suggestions?

![Capture](https://user-images.githubusercontent.com/44419478/54637305-55e19200-4a56-11e9-95d3-4954273037ed.PNG)

![image](https://user-images.githubusercontent.com/44419478/54637353-7578ba80-4a56-11e9-8668-ee806ae69a9d.png)

**Comment by ajb413** [comment]
I tried the [example app](https://github.com/ajb413/chat-engine-webrtc/tree/master/example) and I replaced the reference in the HTML file from 
```
<script src="../dist/chat-engine-webrtc.js"></script>
```
to 
```
<script src="https://cdn.jsdelivr.net/npm/chat-engine-webrtc@latest/dist/chat-engine-webrtc.js"></script>
```
and it appears to be working normally in Chrome. Can you push your code project to your GitHub and send me a link? That way I can better and diagnose your errors.

**Comment by ashbshaw** [comment]
Will do shortly! Thanks so much. This is a school project, and I am in panic mode (hah).

**Comment by ashbshaw** [comment]
https://github.com/cait-sidener/Project-Two

The files in question are video.html and video.js within the "public" folder.
Bear with me, I am new at this. I used your example app to try and get it to work, as you will see.

**Comment by ashbshaw** [comment]
I used you example app to try and get it to work, as you will see.

**Comment by ajb413** [comment]
Looks like your PubNub app is not a ChatEngine app. Log in to PubNub in the box on [this page](https://www.pubnub.com/docs/chat-engine/getting-started#account-setup) and click the "Deploy ChatEngine" button. This will make a new keyset on your PubNub account, enable the right features, and also deploy a PubNub Function that acts as the back end server for your Chat app. This is all free by the way. Insert those new Pub/Sub keys into your application source code. That should fix some of your errors. Let me know if there are more errors.

**Comment by ashbshaw** [comment]
Thank you! I will give that a try. Much appreciated.

**Comment by ashbshaw** [comment]
Well, that fixed the errors. Dumb mistake. Thanks for your help!
